-- Allow manual lot_no assignment so we can reuse the next available number after deletions.
-- Run in Supabase SQL Editor.

alter table if exists public.lots
  alter column lot_no set generated by default;

do $$
begin
  if exists (select 1 from public.lots) then
    perform setval(
      'public.lots_lot_no_seq',
      (select max(lot_no) from public.lots),
      true
    );
  else
    perform setval(
      'public.lots_lot_no_seq',
      1,
      false
    );
  end if;
end $$;
